# Generated by Django 4.0.6 on 2022-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='company_email_address',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
