# Generated by Django 4.0.6 on 2022-07-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0002_customer_email_generalsettings_company_email_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
    ]
