# Generated by Django 4.0.6 on 2022-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0003_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='active',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='actual_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
