# Generated by Django 4.0.6 on 2022-07-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0004_generalsetting_active_rentalcontract_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='currency',
            field=models.CharField(default='RSD', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='currency',
            field=models.CharField(default='RSD', max_length=3),
        ),
    ]
