# Generated by Django 4.0.6 on 2022-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0005_rentalcontract_currency_alter_rentalitem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
