# Generated by Django 4.0.6 on 2022-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0006_alter_rentalitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='currency',
            field=models.TextField(default='RSD', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='notes',
            field=models.TextField(max_length=600),
        ),
    ]
