# Generated by Django 4.0.6 on 2022-07-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0008_alter_customer_note_alter_rentalitem_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item categories'},
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('PP', 'Private person'), ('CP', 'Company')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
