# Generated by Django 4.0.6 on 2022-07-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0009_alter_itemcategory_options_customer_customer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_address',
        ),
    ]
