# Generated by Django 4.0.6 on 2022-07-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syrent_app', '0010_rename_email_customer_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_contact',
            new_name='phone',
        ),
    ]
